=== simplity/forms/fm-all/simplity-core/src/main/resources/schema/app.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://simplity.org/schemas/app",
  "title": "Application Configuration Parameters",
  "description": "Schema for app.json",
  "required": ["name"],
  "additionalProperties": false,
  "properties": {
    "name": {
      "title": "App Name",
      "description": "Name of the App",
      "$ref": "#/$defs/name"
    },
    "maxLengthForTextField": {
      "title": "Max Length for TextField",
      "description": "Any field langer than this is to be rendered as Text Area",
      "type": "integer",
      "defaultValue": 199
    },
    "tenantFieldName": {
      "title": "Tenant Field Name",
      "description": "Required in a multi-tenant app. Name of the field that has the tenant-id",
      "$ref": "#/$defs/name"
    },
    "tenantDbName": {
      "title": "Tenant Db Column Name",
      "description": "Required in a multi-tenant app. Standard column name used in every tenant-specific table.",
      "$ref": "#/$defs/name"
    },
    "valueSchemas": {
      "title": "Value Schemas",
      "description": "Schemas to validate values. These are used to validate input to API's as well as user-inputs in a client-form",
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z_][a-zA-Z0-9_]$": {
          "title": "Value Schema",
          "description": "validation rules for a value",
          "$ref": "#/$defs/valueSchema"
        }
      }
    },
    "valueLists": {
      "title": "List of value-label pairs",
      "description": "List of values and lables that can be used for validating a field, as well as rendering a drop-down",
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z_][a-zA-Z0-9_]$": {
          "title": "Value List",
          "description": "List of valid values for a field",
          "$ref": "#/$defs/valueList"
        }
      }
    }
  },
  "$defs": {
    "name": {
      "description": "suitable to be used as an entity name in a programming language.",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]$"
    },
    "valueSchema": {
      "type": "object",
      "required": ["valueType"],
      "additionalProperties": false,
      "properties": {
        "valueType": {
          "type": {
            "enum": [
              "text",
              "integer",
              "decimal",
              "boolean",
              "date",
              "timestamp"
            ]
          }
        },
        "errorId": { "$ref": "#/$defs/name" }
      },
      "allOf": [
        {
          "if": { "properties": { "valueType": { "const": "text" } } },
          "then": {
            "required": ["maxLength"],
            "properties": {
              "pattern": {
                "title": "Pattern",
                "description": "Pattern the value should conform to. Must be a sommon subset of patterns supported by most languages, specifically java and javascript",
                "type": "string"
              },
              "minLength": { "type": "integer", "default": 1 },
              "maxLength": { "type": "integer" }
            }
          }
        },
        {
          "if": { "properties": { "valueType": { "const": "integer" } } },
          "then": {
            "required": ["maxValue"],
            "properties": {
              "minValue": { "type": "integer" },
              "maxValue": { "type": "integer" }
            }
          }
        },
        {
          "if": { "properties": { "valueType": { "const": "decimal" } } },
          "then": {
            "required": ["maxValue", "nbrFractions"],
            "properties": {
              "minValue": { "type": "number" },
              "maxValue": { "type": "number" },
              "nbrFractions": { "type": "integer" }
            }
          }
        },
        {
          "if": { "properties": { "valueType": { "const": "date" } } },
          "then": {
            "required": ["maxFutureDays", "maxPastDays"],
            "properties": {
              "maxFutureDays": { "type": "integer" },
              "maxPastDays": { "type": "integer" }
            }
          }
        }
      ]
    },
    "valueList": {
      "type": "object",
      "required": ["listType"],
      "additionalProperties": false,
      "properties": {
        "listType": {
          "type": {
            "enum": ["simple", "keyed", "runtime"]
          }
        }
      },
      "allOf": [
        {
          "if": { "properties": { "listType": { "const": "simple" } } },
          "then": {
            "required": ["list"],
            "properties": {
              "list": { "$ref": "#/$defs/simpleList" }
            }
          }
        },
        {
          "if": { "properties": { "listType": { "const": "keyed" } } },
          "then": {
            "required": ["keys"],
            "properties": {
              "keys": { "$ref": "#/$defs/keyedList" }
            }
          }
        },
        {
          "if": { "properties": { "listType": { "const": "runtime" } } },
          "then": {
            "required": ["dbParams"],
            "properties": {
              "dbTableName": {
                "title": "Table Name",
                "description": "Table or View that has the required data for this list",
                "$ref": "#/$defs/name"
              },
              "dbColumn1": {
                "title": "Column Name for Value",
                "description": "Column Name for Value",
                "$ref": "#/$defs/name"
              },
              "dbColumn2": {
                "title": "Column Name for Label",
                "description": "Column Name for Value",
                "$ref": "#/$defs/name"
              },
              "keyColumn": {
                "title": "Column Name for Key",
                "description": "Required if this is a keyed-list.",
                "$ref": "#/$defs/name"
              },
              "tenantColumn": {
                "title": "Tenant Column Name",
                "description": "Relevant if the table is multi-tenant",
                "$ref": "#/$defs/name"
              },
              "activeColumn": {
                "title": "Active Column Name",
                "description": "Relevant if the table has a boolean field for active rows",
                "$ref": "#/$defs/name"
              },
              "keyIsNumeric": {
                "title": "Is Key Numeric?",
                "description": "Key field value type could be numeric or text",
                "type": "boolean"
              },
              "valueIsNumeric": {
                "title": "Is Value Numeric?",
                "description": "Value could be numeric or text",
                "type": "boolean"
              },
              "parentTable": {
                "title": "Parent Table Name",
                "description": "This is specified if all keys are to be extracted, and list for each key is to be extracted. This is similar to keyed-list except that it is extracted once at run time",
                "$ref": "#/$defs/name"
              },
              "parentIdColumnName": {
                "title": "Parent id/value column name",
                "description": "Parent id/value column name",
                "$ref": "#/$defs/name"
              },
              "parentNameColumnName": {
                "title": "Parent name/label column name",
                "description": "Parent name/label column name",
                "$ref": "#/$defs/name"
              }
            }
          }
        }
      ]
    },
    "simpleList": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["value", "label"],
        "properties": {
          "value": {
            "type": ["string", "integer"]
          },
          "label": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "keyedList": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/simpleList"
      }
    }
  }
}

=== simplity/forms/fm-all/simplity-example/resources/spec/application.json
{
  "name": "banyaanTree",
  "tenantFieldName": "instituteId",
  "tenantDbName": "institute_id",
  "maxLengthForTextField": 199,
  "valueLists": {
    "instituteList": {
      "listType": "runtime",
      "dbTableName": "institutes",
      "dbColumn1": "institute_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "trust_id",
      "keyIsNumeric": true,
      "activeColumn": "is_active"
    },
    "departmentList": {
      "listType": "runtime",
      "dbTableName": "departments",
      "dbColumn1": "department_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "activeColumn": "is_active",
      "tenantColumn": "institute_id"
    },
    "designationList": {
      "listType": "runtime",
      "dbTableName": "designations",
      "dbColumn1": "designation_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "activeColumn": "is_active",
      "tenantColumn": "institute_id"
    },
    "degreeList": {
      "listType": "runtime",
      "dbTableName": "degrees",
      "dbColumn1": "degree_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "activeColumn": "is_active",
      "tenantColumn": "institute_id"
    },
    "allSubjectList": {
      "listType": "runtime",
      "dbTableName": "all_subject_list",
      "dbColumn1": "offered_subject_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "department_id",
      "keyIsNumeric": true,
      "tenantColumn": "institute_id"
    },
    "offeredSubjectList": {
      "listType": "runtime",
      "dbTableName": "offered_subject_list",
      "dbColumn1": "offered_subject_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "department_id",
      "keyIsNumeric": true,
      "tenantColumn": "institute_id"
    },
    "taughtSubjectList": {
      "listType": "runtime",
      "dbTableName": "taught_subject_list",
      "dbColumn1": "offered_subject_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "department_id",
      "keyIsNumeric": true,
      "tenantColumn": "institute_id"
    },
    "programList": {
      "listType": "runtime",
      "dbTableName": "programs",
      "dbColumn1": "program_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "department_id",
      "keyIsNumeric": true,
      "activeColumn": "is_active",
      "tenantColumn": "institute_id"
    },
    "subjectTypeList": {
      "listType": "runtime",
      "dbTableName": "subject_types",
      "dbColumn1": "subject_type_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "activeColumn": "is_active",
      "tenantColumn": "institute_id"
    },
    "levelList": {
      "listType": "runtime",
      "dbTableName": "levels",
      "dbColumn1": "level_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "degree_id",
      "keyIsNumeric": true
    },
    "programLevelList": {
      "listType": "runtime",
      "dbTableName": "program_levels",
      "dbColumn1": "level_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "program_id",
      "keyIsNumeric": true
    },
    "sectionList": {
      "listType": "runtime",
      "dbTableName": "sections",
      "dbColumn1": "section_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "activeColumn": "is_active"
    },
    "levelSectionList": {
      "listType": "runtime",
      "dbTableName": "level_section_details",
      "dbColumn1": "level_section_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "level_id",
      "keyIsNumeric": true,
      "activeColumn": "is_active"
    },
    "roleList": {
      "listType": "runtime",
      "dbTableName": "roles",
      "dbColumn1": "role_id",
      "valueIsNumeric": true,
      "dbColumn2": "role_name",
      "activeColumn": "is_active",
      "tenantColumn": "institute_id"
    },
    "seasonList": {
      "listType": "runtime",
      "dbTableName": "seasons",
      "dbColumn1": "season_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "activeColumn": "is_active",
      "tenantColumn": "institute_id"
    },
    "assessmentSchemeList": {
      "listType": "runtime",
      "dbTableName": "assessment_schemes",
      "dbColumn1": "assessment_scheme_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "tenantColumn": "institute_id"
    },
    "assessmentItemList": {
      "listType": "runtime",
      "dbTableName": "assessment_items",
      "dbColumn1": "seq_no",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "assessment_scheme_id",
      "keyIsNumeric": true,
      "tenantColumn": "institute_id"
    },
    "subjectSectionList": {
      "listType": "runtime",
      "dbTableName": "subject_section_list",
      "dbColumn1": "subject_section_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "offered_subject_id",
      "keyIsNumeric": true
    },
    "evaluatorList": {
      "listType": "runtime",
      "dbTableName": "evaluators",
      "dbColumn1": "evaluator_id",
      "valueIsNumeric": true,
      "dbColumn2": "name",
      "keyColumn": "offered_subject_id",
      "keyIsNumeric": true,
      "tenantColumn": "institute_id"
    },
    "accountStatus": {
      "listType": "simple",
      "list": [
        {
          "value": "Active",
          "label": "Active"
        },
        {
          "value": "Suspended",
          "label": "Suspended"
        },
        {
          "value": "Closed",
          "label": "Closed"
        }
      ]
    },
    "userType": {
      "listType": "runtime",
      "list": [
        {
          "value": "student",
          "label": "student"
        },
        {
          "value": "staff",
          "label": "staff"
        },
        {
          "value": "admin",
          "label": "admin"
        },
        {
          "value": "guardian",
          "label": "guardian"
        },
        {
          "value": "trustee",
          "label": "trustee"
        }
      ]
    },
    "instituteType": {
      "listType": "simple",
      "list": [
        {
          "value": "DSERTPS",
          "label": "Karnataka State Syllabus Primary School"
        },
        {
          "value": "DSERTPHS",
          "label": "Karnataka State Syllabus Higher School"
        },
        {
          "value": "CBSE ",
          "label": "CBSE"
        },
        {
          "value": "ENG_A_VTU",
          "label": "Engineering College (Automonus Under VTU)"
        },
        {
          "value": "ENG_VTU",
          "label": "Engineering College ( VTU)"
        }
      ]
    },
    "admissionQuota": {
      "listType": "simple",
      "list": [
        {
          "value": "CET",
          "label": "CET"
        },
        {
          "value": "COMEDK",
          "label": "COMEDK"
        },
        {
          "value": "CETSNQ",
          "label": "CET-SNQ"
        },
        {
          "value": "MANG",
          "label": "MANAGEMENT"
        },
        {
          "value": "NRI",
          "label": "NRI"
        },
        {
          "value": "GOI",
          "label": "GOI"
        },
        {
          "value": "Other",
          "label": "Other"
        }
      ]
    },
    "religion": {
      "listType": "simple",
      "list": [
        {
          "value": "Hindu",
          "label": "Hindu"
        },
        {
          "value": "Muslim",
          "label": "Muslim"
        },
        {
          "value": "Christian",
          "label": "Christian"
        },
        {
          "value": "Sikh",
          "label": "Sikh"
        },
        {
          "value": "Jain",
          "label": "Jain"
        },
        {
          "value": "Others",
          "label": "Other"
        }
      ]
    },
    "relationType": {
      "listType": "simple",
      "list": [
        {
          "value": "Mother",
          "label": "Mother"
        },
        {
          "value": "Father",
          "label": "Father"
        },
        {
          "value": "Legal Guardian",
          "label": "Legal Guardian"
        }
      ]
    },
    "documentType": {
      "listType": "simple",
      "list": [
        {
          "value": "Marks Card",
          "label": "Marks Card"
        },
        {
          "value": "Certificate",
          "label": "Ceritifcate (e.g: Birth Certificate etc)"
        },
        {
          "value": "Photo",
          "label": "Photo"
        },
        {
          "value": "Govt Id",
          "label": "Govt Id(e.g.: Passport, DL etc)"
        }
      ]
    },
    "domicileState": {
      "listType": "simple",
      "list": [
        {
          "value": "Karnataka",
          "label": "Karnataka"
        },
        {
          "value": "Non-Karnataka",
          "label": "Non-Karnataka"
        },
        {
          "value": "Foreign",
          "label": "Foreign"
        }
      ]
    },
    "gender": {
      "listType": "simple",
      "list": [
        {
          "value": "Male",
          "label": "Male"
        },
        {
          "value": "Female",
          "label": "Female"
        },
        {
          "value": "Others",
          "label": "Others"
        },
        {
          "value": "Not Applicable",
          "label": "Not Applicable"
        }
      ]
    },
    "bloodGroup": {
      "listType": "simple",
      "list": [
        {
          "value": "O -ve",
          "label": "O -ve"
        },
        {
          "value": "O +ve",
          "label": "O +ve"
        },
        {
          "value": "A -ve",
          "label": "A -ve"
        },
        {
          "value": "A +ve",
          "label": "A +ve"
        },
        {
          "value": "B -ve",
          "label": "B -ve"
        },
        {
          "value": "B +ve",
          "label": "B +ve"
        },
        {
          "value": "AB -ve",
          "label": "AB -ve"
        },
        {
          "value": "AB +ve",
