=== simplity/forms/fm-all/gen/src/main/resources/schema/formSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Schema for form. file type *.frm.json",
    "required": [
        "name",
        "recordName"
    ],
    "properties": {
        "description": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "recordName": {
            "type": "string"
        },
        "operations": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "get",
                    "create",
                    "update",
                    "filter",
                    "bulk",
                    "delete"
                ]
            }
        },
        "controls": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "controlType"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "controlType": {
                        "type": "string",
                        "enum": [
                            "hidden",
                            "input",
                            "dropDown",
                            "checkBox",
                            "radio",
                            "output",
                            "password"
                        ]
                    },
                    "label": {
                        "type": "string"
                    },
                    "placeHolder": {
                        "type": "string"
                    },
                    "width": {
                        "type": "integer"
                    },
                    "colunUnits": {
                        "type": "integer"
                    }
                },
                "additionalProperties": false
            }
        },
        "linkedForms": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "formName",
                    "isTabular"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "formName": {
                        "type": "string"
                    },
                    "isEditable": {
                        "type": "boolean"
                    },
                    "isTabular": {
                        "type": "boolean"
                    },
                    "minRows": {
                        "type": "integer"
                    },
                    "maxRows": {
                        "type": "integer"
                    },
                    "errorId": {
                        "type": "string"
                    },
                    "parentLinkFields": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "childLinkFields": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false
}

=== simplity/forms/fm-all/example/resources/spec/form/marksEntry.frm.json
{
    "name": "marksEntry",
    "description": "used for marks entry page. linked form to get rows for students ",
    "recordName": "subjectSectionDetail",
    "operations": [
        "get",
        "update"
    ],
    "linkedForms": [
        {
            "name": "students",
            "formName": "marksForAssessment",
            "isEditable": false,
            "isTabular": true,
            "minRows": 1
        }
    ],
    "controls": [
        {
            "name": "subjectSectionId",
            "controlType": "hidden"
        },
        {
            "name": "subjectName",
            "controlType": "output"
        },
        {
            "name": "sectionName",
            "controlType": "output"
        }
    ]
}

=== simplity/forms/fm-all/example/resources/spec/form/studentDetail.frm.json
{
    "name": "studentDetail",
    "recordName": "studentDetail",
    "operations": [
        "get",
        "create",
        "update",
        "filter"
    ],
    "controls": [
        {
            "name": "studentId",
            "controlType": "hidden"
        },
        {
            "name": "instituteId",
            "controlType": "hidden"
        },
        {
            "name": "departmentId",
            "controlType": "dropDown",
            "label": "Department"
        },
        {
            "name": "departmentName",
            "controlType": "input",
            "label": "Department Name"
        },
        {
            "name": "name",
            "controlType": "input",
            "label": "Level"
        },
        {
            "name": "usn",
            "controlType": "input",
            "label": "USN"
        },
        {
            "name": "phoneNumber",
            "controlType": "input",
            "label": "Phone"
        }
    ]
}

=== simplity/forms/fm-all/example/resources/spec/form/studentCieDetail.frm.json
{
 	"name": "studentCieDetail",
    "recordName": "studentCieDetail",
    "operations": [
        "get",
        "create",
        "update",
        "filter"
    ],
    "controls": [
        {
            "name": "studentId",
            "controlType": "hidden"
        },
        {
        	"name":"subjectSectionId",
        	"controlType":"hidden"
        },
        {
            "name": "departmentName",
            "controlType": "output",
            "label": "Department Name"
        },
        {
            "name": "name",
            "controlType": "output",
            "label": "Student Name"
        },
        {
            "name": "usn",
            "controlType": "output",
            "label": "USN"
        },
        {
            "name": "eligibility",
            "controlType": "output",
            "label": "Eligibility"
        },
        {
            "name": "test1",
            "controlType": "output",
            "label": "Test 1"
        },
        {
            "name": "test2",
            "controlType": "output",
            "label": "Test 2"
        },
        {
            "name": "test3",
            "controlType": "output",
            "label": "Test 3"
        },
        {
            "name": "quiz1",
            "controlType": "output",
            "label": "Quiz 1"
        },
        {
            "name": "quiz2",
            "controlType": "output",
            "label": "Quiz 2"
        },
        {
            "name": "theoryCie",
            "controlType": "output",
            "label": "Theory Marks"
        },
        {
            "name": "theoryClassesHeld",
            "controlType": "output",
            "label": "theory Classes Held"
        },
        {
        	"name": "theoryClassesAttended",
            "controlType": "output",
            "label": "theory Classes Attended"
        },
        {
        	"name": "theoryClassesPercentage",
            "controlType": "output",
            "label": "theory Classes Percentage"
        }, 
        {
        	"name": "practicalCie",
            "controlType": "output",
            "label": "Practicals Cie"
        },
        {
        	"name": "practicalClassesHeld",
            "controlType": "output",
            "label": "Practical Classes Held"
        },
        {
        	"name": "practicalClassesAttended",
            "controlType": "output",
            "label": "Practical Classes Attended"
        },
        {
        	"name": "practicalClassesPercentage",
            "controlType": "output",
            "label": "Practical Classes Percentage"
        },
        {
        	"name": "selfStudy",
            "controlType": "output",
            "label": "Self Study"
        },
        {
        	"name": "practicalMarks",
            "controlType": "output",
            "label": "Practicals Marks"
        },
        {
        	"name": "totalCie",
            "controlType": "output",
            "label": "Total Cie"
        }
    ]
}
